import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Navbar, Sidebar} from "@/components";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Serve Yours",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`inter.className `}>

      <div className="flex  bg-gray-100 ">
      <Sidebar/>
      <div className="flex-1 flex flex-col max-h-screen overflow-y-auto">
        <Navbar/>
      <main className="flex-1 p-6">
        {children}
      </main>
      </div>
    </div>
    </body>
    </html>
  );
}
